---
- name: Deploy a static file to remote Apache server
  hosts: webservers
  become: true

  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: Stop and disable Nginx if running
      service:
        name: nginx
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Stop any process using port 80
      shell: |
        fuser -k 80/tcp || true
      ignore_errors: yes

    - name: Ensure Apache is stopped before restart
      service:
        name: apache2
        state: stopped
      ignore_errors: yes

    - name: Create destination directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Copy index.html file to Apache root
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Test Apache configuration
      command: apache2ctl configtest
      register: apache_configtest
      changed_when: false
      failed_when: "'Syntax OK' not in apache_configtest.stderr"

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted

